export const E_SORTING_OPTIONS = {
  ID_ASCENDING: "ID_ASCENDING",
  ID_DESCENDING: "ID_DESCENDING",
  NAME_LEXICOGRAPHICALLY_ASCENDING: "NAME_LEXICOGRAPHICALLY_ASCENDING",
  NAME_LEXICOGRAPHICALLY_DESCENDING: "NAME_LEXICOGRAPHICALLY_DESCENDING",
  PHONE_ASCENDING: "PHONE_ASCENDING",
  PHONE_DESCENDING: "PHONE_DESCENDING",
} as const

export const E_FORM_STATUS = {
  READY: 0,
  WORKING: 1,
  SUCCESS: 2,
  ERROR: 3,
} as const
